# -*- coding: utf-8 -*-
"""Korean per-field help (ported from the web GUI ARG_HELP_KO) → kohya GUI
component `info=` tooltips. Keyed by the form field name; reg() attaches it.
"""

ARG_HELP = {
    "attn_mode": "attention 구현 방식 선택 (sageattn은 추론 전용, --sdpa 무시)",
    "blocks_to_swap": "forward/backward 중 swap할 블록 수 [실험적]",
    "caption_tag_dropout_rate": "쉼표 구분 토큰 드롭아웃 비율 (0.0~1.0)",
    "constantcosine_tail_epochs": "use_constantcosine 시 constant 단계 뒤에 덧붙일 cosine 감쇠 epoch 수 (0=off)",
    "gradient_accumulation_steps": "업데이트 전 누적할 gradient step 수",
    "gradient_checkpointing": "gradient checkpointing 활성화",
    "huber_c": "Huber 손실 감쇠 파라미터 (기본 0.1)",
    "huber_schedule": "Huber 손실 스케줄링 방식 (기본 snr)",
    "log_every_n_steps": "N 글로벌 스텝마다만 스텝 메트릭 출력 (기본: 1)",
    "logit_mean": "logit_normal 가중 방식의 평균",
    "logit_std": "logit_normal 가중 방식의 표준편차",
    "loss_type": "손실 함수 종류 (L1/L2/Huber/smooth L1/pseudo-Huber, 기본 L2)",
    "lr_scheduler_min_lr_ratio": "초기 LR 대비 최소 LR 비율 (cosine min-lr/warmup decay용)",
    "lr_scheduler_type": "LR 스케줄러 (dotted path; 보통 자체 warmup → lr_warmup_steps 0). schedule-free 옵티마이저는 자동 우회",
    "max_grad_norm": "최대 gradient 노름 (0=클리핑 없음)",
    "mixed_precision": "혼합 정밀도 (Anima는 bf16, fp16/no는 미검증)",
    "network_train_unet_only": "U-Net만 학습",
    "optimizer_type": "옵티마이저 (kohya 빌트인 + vendored zoo ~89종; 친근한 이름 CAME/Prodigy/ADOPT… 또는 dotted path)",
    "output_config": "커맨드라인 인자를 .toml 파일로 출력",
    "output_dir": "학습 모델 출력 디렉터리",
    "qwen3_max_token_length": "Qwen3 토크나이저 최대 토큰 길이 (기본: 512)",
    "resume": "학습 재개용 저장된 state",
    "sample_prompts": "샘플 이미지 생성용 프롬프트 파일",
    "save_every_n_epochs": "N epoch마다 체크포인트 저장",
    "save_precision": "저장 정밀도 (None=학습 weight dtype)",
    "save_state": "모델 저장 시 학습 state(optimizer 등) 함께 저장",
    "sigmoid_scale": "sigmoid 타임스텝 샘플링 스케일 (기본: 1.0)",
    "t_max": "학습 sigma 범위 상한 — flow-matching sigma 0.0~1.0 (kohya max_timestep 아님, 0~1000 아님! 기본 1.0)",
    "t_min": "학습 sigma 범위 하한 — flow-matching sigma 0.0~1.0 (kohya min_timestep 아님, 0~1000 아님! 기본 0.0)",
    "target_res": "데이터셋 전처리에 쓴 멀티스케일 constant-token tier (512 768 896 1024 1280 1536), 디스크상 모든 tier 나열 필요",
    "timestep_sampling": "타임스텝 샘플링 방식 (기본: sigmoid)",
    "torch_compile": "torch.compile 사용 (PyTorch 2.0+ 필요)",
    "use_constantcosine": "constant→cosine 원클릭: 계획된 학습은 constant LR로 돌리고, 이후 constantcosine_tail_epochs만큼 cosine 감쇠(LR→min)를 같은 런에서 연장 (lr_scheduler 무시)",
    "use_shuffled_caption_variants": "TE 캐시의 전처리된 캡션 셔플 변형을 샘플마다 무작위 사용",
    "use_shuffled_caption_variants_only": "원본 v0 제외, 셔플된 v1~v{N-1}만 균등 샘플링",
    "use_text_cache": "TE 출력을 디스크에 캐시 후 학습 시 읽기 (false면 라이브 인코딩)",
    "use_vae_cache": "VAE 잠재값을 디스크에 캐시 후 학습 시 읽기 (false면 라이브 인코딩)",
    "weighting_scheme": "타임스텝 분포 가중 방식 (기본: uniform)",
    # --- auto-translated schema arg help (131 entries) ---
    "activation_memory_budget": "torch.compile AOT partitioner의 backward용 activation 메모리 보존 비율(0~1); 1.0 미만이면 저렴한 중간값을 backward에서 재계산. torch_compile 시에만 적용, gradient_checkpointing 시 무시",
    "artist_filter": "caption에 `@<artist>` 태그가 있는 이미지만 학습; 결과는 output/ckpt-artist/로 리다이렉트",
    "attn_softmax_scale": "attention용 custom softmax scale (기본 1/sqrt(head_dim)); 값이 크면 attention이 날카로워지고 bf16 정밀도 향상",
    "base_weights": "학습 전 모델에 merge할 network weights",
    "base_weights_multiplier": "학습 전 merge할 network weights의 multiplier",
    "byg_alpha": "BYG prior 내 MSE 크기 anchor 가중치: L_prior = L_dir + alpha*L_MSE (논문 §4.2)",
    "byg_ema_decay": "학습 가능한 LoRA weight의 bootstrap 복사본 EMA decay. 0.0(기본)은 주기적 hard snapshot 사용, >0이면 per-step EMA 이동평균",
    "byg_identity_prob": "warmup 이후 step이 무작위 identity step일 확률 (논문 App. B.1 = 0.15); identity 붕괴 방지 regularizer",
    "byg_identity_warmup_steps": "처음 N step을 identity-only로 학습해 편집 전 condition 사용법 학습 (논문 App. B.1 = 200)",
    "byg_lambda_cycle": "cycle-consistency loss L_cycle 가중치 (논문 Eq. 5, 기본 1.0)",
    "byg_lambda_id": "anti-collapse identity loss L_id 가중치 (논문 Eq. 5, 기본 0.2); 독립 graph로 backward해 peak VRAM 절감",
    "byg_lambda_prior": "DDS-style prior loss L_prior 가중치 (논문 Eq. 5, 기본 1.0)",
    "byg_prior_symmetric": "prior loss를 reverse pass에도 적용 (L_prior^fwd + L_prior^rev, 논문 Eq. 5). 기본 on(v2); 끄면 v1 fwd-only로 frozen-base forward 2회 절감",
    "byg_rollout_sigmas": "균일 byg_rollout_steps 대신 명시적 비균일 rollout sigma 격자. 1.0에서 0.0까지 엄격 감소 리스트(n+1 노드 → n Euler step). TOML은 float 배열, CLI는 콤마 구분. 기본 None = 균일",
    "byg_rollout_steps": "pseudo-noisy-target y~_t와 clean y~_0을 만드는 bootstrap rollout의 Euler step 수 n (논문 App. B.1 = 10). byg_rollout_sigmas 지정 시 무시",
    "byg_snapshot_every": "bootstrap rollout용 frozen weight snapshot을 N optimizer step마다 hard-refresh (v1 EMA-free 경로). byg_ema_decay > 0이면 무시",
    "byg_text_dir": "이미지별 BYG edit-tuple sidecar(<stem>_byg.safetensors) 디렉터리. 기본 post_image_dataset/byg",
    "cache_info": "데이터셋 로딩 가속을 위한 메타 정보 캐시",
    "cache_llm_adapter_outputs": "LLM adapter 출력(cross-attention embedding)을 TE 캐시에 저장하고 학습 중 adapter 실행 생략. --cache_text_encoder_outputs 필요, LLM adapter LoRA 학습과 비호환",
    "caption_dropout_every_n_epochs": "N epoch마다 모든 caption을 dropout",
    "caption_dropout_rate": "caption dropout 비율 (0.0~1.0)",
    "caption_extension": "caption 파일 확장자",
    "caption_extention": "caption 파일 확장자 (구버전 호환용 철자)",
    "caption_separator": "caption 구분자",
    "checkpointing_epochs": "N epoch마다 재개용 checkpoint 저장 (이전 것 덮어쓰기, 다음 실행 시 자동 resume)",
    "compile_dynamic_seq": "sequence 길이 축만 dynamic으로 표시해 token-count별 그래프 대신 단일 그래프 사용, N개 그래프 컴파일 및 VRAM 피크를 1개로 축소 (기본 ON, multiscale 권장)",
    "compile_inductor_mode": "torch.compile에 전달할 Inductor mode. 'reduce-overhead'는 CUDAGraphs 활성화 — 주소 고정 필요, block swap과 비호환",
    "cond_diff_loss": "cond↔target latent 차이로 per-pixel FM loss 가중 (paired cond≠target 작업에서 편집 영역에 gradient 집중). colorize에는 부적합",
    "cond_diff_loss_blur": "diff map에 적용할 Gaussian sigma (latent px), 영역 + halo 커버 (기본 1.5)",
    "cond_diff_loss_floor": "편집 영역 밖 최소 가중치 (정규화 전), 나머지 영역 유지용 (기본 0.2)",
    "cond_diff_loss_quantile": "diff map의 per-image robust scale, 이 quantile 이상은 최대 가중치로 saturate (기본 0.9)",
    "config_file": "args 대신 .toml로 하이퍼파라미터 전달",
    "config_snapshot": "실제 실행마다 output/<output_name>.snapshot.toml 기록 (출처 + git SHA). --no-config-snapshot로 비활성화",
    "config_strict": "config 스키마 경고(미지정 키, 목록 외 선택)를 에러로 처리",
    "console_log_file": "stderr 대신 파일에 로그 기록",
    "console_log_level": "로깅 레벨 (기본 INFO)",
    "console_log_simple": "간단한 로그 출력",
    "cpu_offload_checkpointing": "[실험적] checkpointing 중 U-Net/DiT 텐서를 CPU로 offload (지원 시)",
    "cross_attn_lr": "cross-attention 레이어 learning rate. None=base LR와 동일, 0=freeze",
    "dataloader_pin_memory": "DataLoader 메모리 pin",
    "dataloader_prefetch_factor": "DataLoader worker의 prefetch_factor (num_workers>0일 때만 유효)",
    "dataset_class": "임의 dataset용 클래스 (package.module.Class)",
    "dataset_repeats": "caption 학습 시 dataset 반복 횟수",
    "debiased_estimation_loss": "debiased estimation loss 사용",
    "debug_dataset": "디버그용으로 이미지를 표시 (학습하지 않음)",
    "discrete_flow_shift": "rectified flow 학습의 timestep 분포 shift (기본 1.0)",
    "dynamo_backend": "torch.compile backend. 'inductor'(기본)=프로덕션, 'eager'=컴파일 비활성(디버그용)",
    "easycontrol_cond_noise_max": "학습 시 cond latent에 더하는 Gaussian noise 상한. sigma~U(0,값)로 cond+sigma*eps 적용, 0.0=비활성. 0.3-0.7로 cond 지배력 약화해 text가 고주파 담당",
    "easycontrol_drop_p": "EasyControl 이미지 conditioning dropout 확률 (이미지 분기 CFG dropout, text dropout과 독립, 기본 0.1)",
    "ema": "Exponential Moving Average 활성화 (--ema_decay 필요)",
    "ema_decay": "EMA decay 비율. 일반값 0.999/0.9999 (기본 0.9999)",
    "ema_device": "EMA shadow 파라미터 device. 'cpu'=GPU VRAM 절약하나 느림 (기본 gpu)",
    "ema_param_multiplier": "EMA 업데이트마다 파라미터에 곱하는 배수 (기본 1.0, 효과 없음)",
    "ema_resume_path": "이전 run의 EMA state를 이어받을 EMA safetensors 경로",
    "ema_use_feedback": "EMA decay를 학습 파라미터에 피드백 (실험적)",
    "ema_use_num_updates": "EMA decay에 warmup 스케줄 적용: min(decay, (1+num_updates)/(10+num_updates))",
    "functional_loss_blocks": "functional MSE loss용 cross_attn.output_proj 출력을 캡처할 DiT block 인덱스 (콤마 구분)",
    "functional_loss_num_runs": "이미지당 기대 inversion run 수 (make invert의 aggregate_by). 매 step 무작위로 하나 샘플 (기본 3)",
    "functional_loss_weight": "functional MSE loss 가중치: (t5+postfix) forward와 inversion forward의 output_proj 캡처 간 MSE, functional_loss_blocks 합산. 0=비활성(기본)",
    "fused_backward_pass": "backward와 optimizer step을 결합해 VRAM 절약",
    "gradient_checkpointing_min_resolution": "tier edge가 이 값 이상인 batch에만 gradient checkpointing 적용 (유효 edge: 512 768 896 1024 1280 1536). 큰 tier만 recompute, 작은 tier는 풀속도 유지",
    "huber_scale": "Huber 손실 scale 파라미터 (기본 1.0)",
    "huggingface_token": "huggingface 토큰",
    "in_json": "데이터셋용 json 메타데이터",
    "initial_epoch": "시작 epoch 번호, 1=첫 epoch (미지정과 동일). lr scheduler에는 영향 없음 — --resume 없으면 scheduler는 0부터 시작",
    "initial_step": "모든 epoch 포함 시작 step 번호, 0=첫 step (미지정과 동일). initial_epoch보다 우선 적용",
    "inversion_dir": "<stem>_inverted_run{i}.safetensors 디렉터리. 설정 시 functional-loss 감독용으로 각 샘플과 함께 inversion 로드",
    "ip_noise_gamma": "input perturbation noise 활성화 (권장값 약 0.1)",
    "ip_noise_gamma_random_strength": "input perturbation noise에 0~ip_noise_gamma 사이 랜덤 강도 사용",
    "liveness_strict": "보조 loss(repa/fera_fecl/soft_tokens 등)가 ON이지만 입력을 소비하지 않으면 학습 중단. 기본 off(LIVENESS: 로그만 남김)",
    "llm_adapter_path": "별도 LLM adapter 가중치 경로. None이면 DiT 파일에 있을 경우 거기서 로드",
    "log_prefix": "각 로그 디렉터리에 붙일 prefix",
    "log_tracker_config": "로깅용 tracker config 파일 경로",
    "lora_fp32_accumulation": "[DEPRECATED, no-op] LoRA/Hydra bottleneck matmul의 fp32 누적은 이제 항상 적용됨. 곧 제거 예정",
    "lora_multiplier": "--lora_path로 병합된 frozen LoRA에 적용할 multiplier",
    "lora_path": "학습 전 DiT에 병합할 사전학습 LoRA 체크포인트 경로. 고정 LoRA 위에 adapter 학습용 (런타임 hook 없이 base에 baked-in)",
    "lr_decay_steps": "lr scheduler의 decay step 수 (기본 0), 또는 train step 비율을 나타내는 float(<1)",
    "lr_scheduler_timescale": "inverse sqrt scheduler의 inverse sqrt timescale (기본값은 num_warmup_steps)",
    "max_validation_steps": "처리할 validation 데이터 최대 개수 (기본: 전체 validation 데이터셋 실행)",
    "metadata_merged_from": "병합 모델 메타데이터용 소스 모델",
    "metadata_thumbnail": "모델 메타데이터용 썸네일 (data URL 또는 파일 경로, data URL로 변환됨)",
    "metadata_trigger_phrase": "모델 메타데이터용 trigger phrase",
    "metadata_usage_hint": "모델 메타데이터용 사용 힌트",
    "no_metadata": "출력 모델에 metadata 저장 안 함",
    "methods_subdir": "method 파일이 있는 configs/ 하위 폴더 (기본 'methods'). GUI용 per-variant 설정은 'gui-methods' 사용",
    "min_snr_gamma": "high loss timestep 가중치 감소용 gamma. 값이 낮을수록 효과 강함 (논문 권장 5)",
    "mlp_lr": "MLP 레이어 learning rate. None=base LR와 동일, 0=freeze",
    "mode_scale": "'mode' weighting scheme의 scale (SD3 mode 샘플링)",
    "mod_lr": "AdaLN modulation 레이어 learning rate. None=base LR와 동일, 0=freeze (mod 레이어는 기본적으로 LoRA에 미포함)",
    "multiscale_loss_weight": "2x 다운샘플 multiscale loss 항 가중치 (0 = 비활성, 기본 0)",
    "network_train_text_encoder_only": "Text Encoder 부분만 학습",
    "no_half_vae": "VAE에 fp16 사용 안 함",
    "path_pattern": "subset image_dir 기준 상대 경로에 적용할 fnmatch glob 필터 (`|`로 대안 구분, 미설정/`*`는 전체)",
    "print_config": "병합된 전체 config (base → preset → method → CLI)를 TOML로 출력 후 종료 (학습 안 함)",
    "prior_loss_weight": "regularization 이미지의 loss 가중치",
    "profile_steps": "지정 step 범위(예 '3-5')에 CUDA profiler 활성화, nsys와 함께 사용",
    "progress_jsonl": "진행 상황 JSONL 이벤트 스트림 경로 (미설정 시 자동 유도, ''/'none'/'off'로 비활성)",
    "pseudo_huber_c": "Pseudo-Huber loss 파라미터 c (작으면 L1, 크면 MSE 유사, 기본 0.03)",
    "qwen_image_vae_2d": "Qwen-Image VAE를 이미지 전용 2D 구현으로 사용 (단일 이미지 시 3D와 수치 동일, 약 2배 빠르고 VRAM 약 1/3)",
    "reg_data_dir": "regularization 이미지 디렉토리",
    "resize_interpolation": "Resize 보간 방식",
    "resume_from_huggingface": "huggingface에서 재개",
    "sample_decode_inline": "각 sampling 직후 sample latent를 PNG로 즉시 decode (true/false 또는 'auto', 기본 'auto')",
    "sample_ratio": "모든 subset의 sample_ratio에 적용할 전역 override (0<r≤1, 미설정 시 각 subset 값 사용)",
    "save_n_epoch_ratio": "checkpoint를 N epoch 비율마다 저장",
    "self_attn_lr": "self-attention 레이어 learning rate (None = 기본 LR, 0 = freeze)",
    "sigmoid_bias": "sigmoid/shift/flux_shift 샘플링의 logit 공간 평균 이동 (>0은 고 σ, <0은 저 σ로 치우침, 기본 0.0)",
    "skip_until_initial_step": "initial_step에 도달할 때까지 학습 건너뛰기",
    "t5_tokenizer_path": "T5 tokenizer 디렉토리 경로 (None이면 번들된 library/anima/configs/t5_old/ 사용)",
    "text_encoder_batch_size": "text encoder batch size (기본 None, dataset의 batch size 사용)",
    "tokenizer_cache_dir": "Tokenizer 캐시 디렉터리 (오프라인 학습용)",
    "train_data_dir": "학습 이미지 디렉터리",
    "unsloth_offload_checkpointing": "activation을 비동기 non-blocking 전송으로 CPU RAM에 offload (--cpu_offload_checkpointing보다 빠름). --cpu_offload_checkpointing / --blocks_to_swap와 병용 불가",
    "use_byg": "BYG 비페어 편집 학습 활성화. BYG 데이터셋(cond_cache_dir 소스 latent + 이미지당 4개 텍스트 conditioning) 필요",
    "use_cmmd": "검증 신호로 CMMD(PE-Core MMD²) 사용. false면 legacy per-σ FM-MSE val만 실행 (저VRAM용)",
    "use_easycontrol": "EasyControl 이미지 conditioning 활성화(VAE latent 기반 확장 self-attn KV). network가 set_cond_tokens 노출 필요",
    "vae_chunk_size": "VAE 인코딩/디코딩 메모리 절약용 공간 chunk 크기. 짝수여야 함. 미지정 시 chunking 비활성",
    "validate_every_n_epochs": "N epoch마다 검증 실행 (기본: 검증셋 있으면 매 epoch)",
    "validate_every_n_steps": "N step마다 검증 실행 (기본: 검증셋 있으면 매 epoch)",
    "validation_baselines": "검증 중 method adapter의 baseline(no_ip / shuffled_ref 등)을 FM-MSE delta 진단으로 실행. false면 생략(IP-Adapter 검증 시간 약 절반)",
    "validation_cfg_scale": "CMMD 검증에 쓰는 CFG scale. 기본 1.0(no CFG, 최속). 4.0이면 production 샘플링과 일치하나 생성 비용 ~2배",
    "validation_sample_steps": "CMMD 검증 시 held-out 항목당 denoising step 수 (기본 20)",
    "validation_seed": "검증셋 셔플 seed, 미지정 시 학습 --seed 사용",
    "validation_sigmas": "검증 손실용 sigma 값 (0.0~1.0). 낮을수록 세부 디테일. 기본 0.1 0.4 0.7 (legacy FM-val 경로)",
    "validation_split": "학습 데이터셋에서 검증용으로 분리할 비율",
    "validation_split_num": "개수 기반 검증 분리(held-out 이미지 수). >0이면 --validation_split보다 우선. CMMD 생성 샘플 수도 결정",
    "vr_fei_sigma_low_div": "x_0^L 생성용 FEI 저역통과 커널 divisor (σ_low = min(H_lat,W_lat)/div). FEI 기본값 4.0과 일치",
    "vr_lambda_beta": "온라인 λ 추정기의 EMA rate: λ_ema ← (1−β)·λ_ema + β·λ_batch. 기본 0.01",
    "vr_loss_weight": "FM 손실에 대한 VR control-variate 보정 가중치. 0=표준 FM(기본), 1.0=논문 레시피. >0이면 step당 adapter zero 상태로 no-grad forward 1회 추가",
    "vr_sigma_min": "VR 손실 분모의 σ_t 하한(AsymFlow §6.1). 1/σ_t 항의 저-σ 불안정 방어. 0이면 비활성",
    "weighted_captions": "표준 스타일(token:1.3) weighted caption 활성화",
}
